{% set name = "dkh" %}
{% set version = "1.2" %}
{% set sha256 = "b8a1dc1df3161938890eb6ef97280a2e99d07f69d5e3b672c48fc4622a872030" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/psi4/{{ name|lower }}/archive/3ba0128.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('dkh', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("fortran") }}
    - cmake
    - ninja
  host:
    - libblas

test:
  commands:
    - ls -l $PREFIX/lib                                         # [unix]
    - ls -l $PREFIX/share/cmake/dkh                             # [unix]
    - dir %PREFIX%\\Library\\lib                                # [win]
    - dir %PREFIX%\\Library\\share\\cmake\\dkh                  # [win]
    # Verify library
    - test -f $PREFIX/lib/libdkh$SHLIB_EXT                      # [unix]
    - test ! -f $PREFIX/lib/libdkh.a                            # [unix]
    - if not exist %PREFIX%\\Library\\lib\\dkh.lib exit 1       # [win]   # ms import lib
    - if not exist %PREFIX%\\Library\\bin\\dkh.dll exit 1       # [win]   # ms dyn lib
    # Verify accessories
    - test -e $PREFIX/include/DKH/DKH_MANGLE.h                  # [unix]
    - test -e $PREFIX/share/cmake/dkh/dkhConfig.cmake           # [unix]
    - if not exist %PREFIX%\\Library\\include\\DKH\\DKH_MANGLE.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\cmake\\dkh\\dkhConfig.cmake exit 1  # [win]
    # Inspect linkage
    - ldd -v $PREFIX/lib/libdkh$SHLIB_EXT                       # [linux and build_platform == target_platform]
    - otool -L $PREFIX/lib/libdkh$SHLIB_EXT                     # [osx]
    - 'objdump.exe -p %PREFIX%\\Library\\bin\\dkh.dll | findstr /i "dll"'  # [win]


about:
  home: http://www.reiher.ethz.ch/software/dkh-x2c.html
  dev_url: https://github.com/psi4/dkh
  license: LGPL-3.0-only
  license_url: https://opensource.org/license/lgpl-3-0/
  license_file:
    - COPYING
    - COPYING.LESSER
  license_family: LGPL
  summary: "Wolf, Reiher, and Hess's Douglas-Kroll-Hess (DKH) relativistic correction"

extra:
  recipe-maintainers:
    - loriab
    - jturney
